# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bharat FM Radio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bharat FM Radio

end
